name: Build web
on:
  push:
    branches:
      - master
      - main
      - v5
      - v3
      - dev
      - own
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run build
    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
    # Files, comma-separated. Supposed PLACEHOLDER in them
        files: 'dist/index.html'
    # Comma-separated pairs PLACEHOLDER=value
        replacements: 'main-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/main-es,runtime-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/runtime-es,polyfills-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/polyfills-es,main-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/main-es,runtime-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/runtime-es,polyfills-es=https://cdn.jsdelivr.net/gh/lovelyqiqi2020/nav@gh-pages/polyfills-es'
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
